[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/api/smm/order"
  to = "https://my.smmgen.com/api/v2"
  status = 200
  force = true

[[redirects]]
  from = "/api/smm/services"
  to = "https://my.smmgen.com/api/v2?key=64994346bbbbeeaa10307df325162283&action=services"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
